pipeline {
    agent any

    triggers {
        pollSCM('H/5 * * * *')
    }
    

    options{
        timeout(time: 30, unit: 'MINUTES')
        timestamps()
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install && lint && build') {
            agent{
                docker{
                    image 'node:22-alpine'

                    reuseNode true
                }
            }
            steps {
                dir('jenskin_app/my-react-app') {
                    sh 'node -v && npm -v'
                    sh 'npm ci'
                    sh 'npm run lint'
                    sh 'npm run build'
                }
                
            }
        }
    }

    post {
        success {
            dir('jenskin_app/my-react-app') {
                 archiveArtifacts artifacts: 'dist/**/*', fingerprint: true, allowEmptyArchive: false
            }
        }
        failure {
            echo "Pipeline failed!"
        }
    }
}
